FROM python:3.10.12-slim

#TODO: Set the working directory


#TODO: Copy the requirements file and install dependencies


#TODO: Copy the contents of the source_code folder


#TODO: Expose the port the app runs on


#TODO: Command to run the application

